name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Reload PythonAnywhere Web App
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with:
        host: 'www.pythonanywhere.com'
        username: neiesc
        api-token: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        domain-name: neiesc.pythonanywhere.com
