# Generated by Django 5.1.7 on 2025-03-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasa_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='question_text',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='pub_date',
            new_name='preco',
        ),
    ]
